### ISSUE TITLE
Idea: External css / js integrity

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-htmlhead#10]
Hey there,
I'd like to incorporate an external CSS file in `'bnomei.htmlhead.css'`, and while `kirby3-fingerprint` is installed, there's currently no option to include its `integrity` value.

**Comment by daybugging** [comment]
full ack

**Comment by bnomei** [comment]
good idea. will add for js as well.

**Comment by bnomei** [comment]
ah yes. just do `https://www.example.com/mystyle.css|sha384-whatever` in the config. use `|` to seperate filename from SRI. works for js as well.
