### ISSUE TITLE
Add async scripts

### ISSUE THREAD

**Issue by seehat** [bnomei/kirby3-htmlhead#20]
Is there a way to output scripts with the `async` attribute?

If not can you add it?

**Comment by bnomei** [comment]
the build in snippet has no support for that yet.
https://github.com/bnomei/kirby3-htmlhead/blob/master/snippets/htmlhead/script-js.php

but you could create your own snippet and just add its filename with to the plugins config array. like [here](https://github.com/bnomei/kirby3-htmlhead/blob/ef527d17d6ec8b593664a4b73c4f537212a2178b/tests/site/config/config.php#L33) but indead of `htmlhead/script-js` you could use your snippets filename.

> TIP: thats how you can basically add anything to this plugin. snippets ftw. :D

**Comment by seehat** [comment]
Ok thank you for your tip! I know this and thought that it would make sense in core, but it's ok for me, when it stays like this.

**Comment by bnomei** [comment]
@seehat  new in https://github.com/bnomei/kirby3-htmlhead/releases/tag/v2.1.9

```
'htmlhead/script-js' => function ($kirby, $site, $page) {
            return ['files' => [
                // NEW !! ARRAY
                [
                    'src' => 'somescript.js', 
                    'async' => true,
                ],
                '/assets/app.js', // STRING
                'https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.min.js|sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=', // STRING|INTEGRIY
            ]];
        },
```
