### ISSUE TITLE
Skip <base> completely

### ISSUE THREAD

**Issue by MaluNoPeleke** [bnomei/kirby3-htmlhead#24]
Can you please add an option to skip the addition of < base > completely?
I want to add anchor links and don't need the < base > element.
I tried it with null but it doesn't skip generating the line and still makes anchor links impossible.
```
    'htmlhead/base' => function ($kirby, $site, $page) {
      return ['href' => 'null'];
    },
```

**Comment by bnomei** [comment]
that makes sense. i will do that asap.

**Comment by bnomei** [comment]
lol. its much easier. you just remove that var => callback thing from the array.

```php
   /*
    'htmlhead/base' => function ($kirby, $site, $page) {
      return ['href' => 'null'];
    },
   */
```

**Comment by bnomei** [comment]
ah. its merged. sorry...
https://github.com/bnomei/kirby3-htmlhead/blob/a6f112129451dd381dc1f3c951c4ab940b94d78f/classes/HTMLHead.php#L16

**Comment by bnomei** [comment]
return ['href' => 'null'];
or
return [];
should work now.
