### ISSUE TITLE
SEO / Opengraph / Twitter cards

### ISSUE THREAD

**Issue by S1SYPHOS** [bnomei/kirby3-htmlhead#8]
Hey there,
great plugin, many thanks are in order - now, it would be great to have an example how you populate SEO / Opengraph meta tags (with custom page methods etc as mentioned in README.md), like you did on your [devkit page](https://kirby3-plugins.bnomei.com)?

PR regarding some minor fixes is up and running :rice_ball: 

// Edit: I'm open to adding twitter card support, too. And what's your standing on `og:locale` and `og:description?` being included by default?

Cheers!

**Comment by bnomei** [comment]
about metatags. the code is available but i agree it should be explained in readme. 
https://github.com/bnomei/kirby3-plugins.bnomei.com/blob/master/site/plugins/metatags/index.php

i will read up on og:locale and og:description and add them. 

you can allways use a custom snippet to add twitter card support. i am not in favor of adding it by default but will add it as unregistered snippet if you PR it.

**Comment by bnomei** [comment]
added example to readme.

about og:locale and og:description. they should work whats you issue there?

**Comment by bnomei** [comment]
use https://github.com/pedroborges/kirby-meta-tags instead
